// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmQ21Kfx9i7nwQOdEm8-KMFbGckp5IU9o',
    appId: '1:858186020830:web:52454b99f69fc8fcaecf4f',
    messagingSenderId: '858186020830',
    projectId: 'chat-app-f0377',
    authDomain: 'chat-app-f0377.firebaseapp.com',
    storageBucket: 'chat-app-f0377.firebasestorage.app',
    measurementId: 'G-C866LB1MC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRjhPXP1Kfp-syxI0kFbV5XM_scbGwUpE',
    appId: '1:858186020830:android:301219b940616351aecf4f',
    messagingSenderId: '858186020830',
    projectId: 'chat-app-f0377',
    storageBucket: 'chat-app-f0377.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsVc38aQt8wg6hWR_EhE_TYYU7rgk0fZw',
    appId: '1:858186020830:ios:399814431b907922aecf4f',
    messagingSenderId: '858186020830',
    projectId: 'chat-app-f0377',
    storageBucket: 'chat-app-f0377.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsVc38aQt8wg6hWR_EhE_TYYU7rgk0fZw',
    appId: '1:858186020830:ios:399814431b907922aecf4f',
    messagingSenderId: '858186020830',
    projectId: 'chat-app-f0377',
    storageBucket: 'chat-app-f0377.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmQ21Kfx9i7nwQOdEm8-KMFbGckp5IU9o',
    appId: '1:858186020830:web:67e48e11f2dd55abaecf4f',
    messagingSenderId: '858186020830',
    projectId: 'chat-app-f0377',
    authDomain: 'chat-app-f0377.firebaseapp.com',
    storageBucket: 'chat-app-f0377.firebasestorage.app',
    measurementId: 'G-39QXK83BPZ',
  );
}
